apiVersion: v1
kind: Service
metadata:
  name: pedelec-damage-service
  namespace: my-namespace
  labels:
    app: damage
spec:
  selector:
    app: damage
  ports:
    - protocol: TCP
      port: 80
      targetPort: damage-api
