apiVersion: apps/v1
kind: Deployment
metadata:
  name: location
  labels:
    app: location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
        - name: location
          image: ghcr.io/mtze/pedelec-location:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
              name: location-api
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
