apiVersion: v1
kind: Service
metadata:
  name: pedelec-damage-service
  labels:
    {{- include "pedelec.labels" . | nindent 4 }}
    app: damage
spec:
  selector:
    app: damage
  ports:
    - protocol: TCP
      port: 80
      targetPort: damage-api
