apiVersion: v1
kind: Service
metadata:
  name: pedelec-location-service
  labels:
    {{- include "pedelec.labels" . | nindent 4 }}
    app: location
spec:
  selector:
    app: location
  ports:
    - protocol: TCP
      port: 80
      targetPort: location-api
