apiVersion: v1
kind: Service
metadata:
  name: pedelec-reservation-service
  labels:
    {{- include "pedelec.labels" . | nindent 4 }}
    app: reservation
spec:
  selector:
    app: reservation
  ports:
    - protocol: TCP
      port: 80
      targetPort: reservation-api
