apiVersion: v1
kind: Pod
metadata:
  name: app1
  namespace: my-namespace
spec:
  containers:
    - name: app1
      image: nginxdemso/hello
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "250m"
          memory: "256Mi"
      ports:
        - containerPort: 80
          name: app1-port
